image:
  repository: 199837183662.dkr.ecr.us-east-2.amazonaws.com/scos/predictive-parking
  tag: latest
  pullPolicy: Always

replicaCount: 1

service:
  type: NodePort
  port: 80

mssql:
  database: parking_prediction

comparedModels: ''

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/tags: scos.delete.on.teardown=true
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/actions.redirect: '{"Type": "redirect", "RedirectConfig":{"Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
  rootDnsZone: smartcolumbusos.com

resources:
  api:
    limits:
      memory: 4Gi
      cpu: "1"
    requests:
      memory: 4Gi
      cpu: "1"
  train:
    limits:
      memory: 5Gi
      cpu: "1"
    requests:
      memory: 5Gi
      cpu: "1"
