apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      serviceAccountName: parking-prediction-api
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        command: ["./start.sh"]
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: SCOS_ENV
          value: {{ .Values.scosEnv }}
        - name: VAULT_ROLE
          value: parking-prediction-api-role
        - name: VAULT_CREDENTIALS_KEY
          value: parking_prediction_api
        resources:
{{ toYaml .Values.resources | indent 10 }}